"""
A collection of constants defining the palette for the application.
"""

# TODO(?): remove `COLOR_` prefix?
COLOR_BLACK = "#000"
COLOR_WHITE = "#fff"
COLOR_SILVER = "#cce"
COLOR_GRAY = "#99b"
COLOR_DARKGRAY = "#336"
COLOR_CHARCOAL = "#225"
COLOR_BLUE = "#36c"
COLOR_DARKBLUE = "#029"
COLOR_LIGHTBLUE = "#9cf"
COLOR_RED = "#c36"
COLOR_DARKRED = "#506"
COLOR_LIGHTRED = "#f9c"
COLOR_YELLOW = "#fc3"
COLOR_BROWN = "#743"
COLOR_SAND = "#965"
COLOR_LAVENDER = "#99f"
COLOR_PURPLE = "#43c"
COLOR_VIOLET = "#209"
COLOR_CYAN = "#9ff"
COLOR_TURQUOISE = "#3cc"
COLOR_TEAL = "#07a"
