"""
A collection of ui constants.
"""

BOARD_CELL_SIZE = 48
MARBLE_SIZE = BOARD_CELL_SIZE * 7 / 8

BOARD_SIZE = 5
BOARD_MAX_COLS = BOARD_SIZE * 2 - 1
BOARD_WIDTH = BOARD_CELL_SIZE * BOARD_MAX_COLS
BOARD_HEIGHT = BOARD_CELL_SIZE * BOARD_MAX_COLS * 7 / 8
